name: ci-cd

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t my-reactjs-app -f Dockerfile .

      - name: Run Docker container
        run: docker run -d --name reactjs-container -p 3000:3000 my-reactjs-app
